### ISSUE TITLE
[proposal] better lifecycle management

### ISSUE THREAD

**Issue by jschwinger233** [projecteru2/core#195]
![lifecycle](https://user-images.githubusercontent.com/6435624/78232692-343f3580-7507-11ea-9b32-18e6df078b0e.png)

1. running, stopped, removed 都是由 agent 上报的远程实际状态, 只有 created 是 core 调用 API 成功后就认为成功.
2. running 细分为 healthy / unhealthy, 还是老设计
3. stopped, removed 都是靠监听 docker events
4. unknown 是 core 记录的 status 超时后的状态, agent 没有定时上报

直接动机是使资源管理更加清晰, created 成功即扣资源, 写元数据; 发现 removed 就还数据.

另外的好处是:

1. 改善 zero refresh. 比方说重启 agent 导致 overwatch 的 refresh 风暴, 在细分了生命期和状态机之后, overwatch 可以精准 refresh 具体的状态变化, 对于重启 agent 而言 watch 到的信息是 `running -> running`, 那就无视就好了. 
2. 新增了 unknown 状态, 让我们能够处理`节点下线`的情况, 之前节点下线只会导致 key expire, 然后收到的是 not running & not healthy 的状态, 无法得知节点下线事件.
3. 新增 removed 状态让我们能够处理外部事件, 比如我手动 docker rm 一个 eru 容器; 在新设计下, remove 事件能被 agent 监听到, 然后 core 能够处理 agent 的上报, 归还资源.
4. 精细化资源管理, 之前只要调用 start api 成功就扣资源, remove api 成功就还资源, 现在完全依赖 agent 上报生命状态, 能够应对更多意外情况.

当然这是一个巨大而激进的改动, 是否走向这个方向还需讨论.

**Comment by CMGS** [comment]
一条条说
1. 首先 agent 和 core 是完全解耦的，我觉得应该先从一个视角解决现有问题再考虑另外一个视角。这里来看你耦合了 agent 和 core，这样的坏处在于 core 是否需要知道有 docker events 的存在，多 core 状态一致性怎么办。
2. 没啥，就是老设计
3. 这一点我的问题在于既然都 removed 了，如果对于外部用户来说知道这个状态意味着元数据就不删除？
4. unknown 的问题在于，现在 status 的反馈是单向的，这样好处在于 core 其实无状态，也不关心资源使用方状态，agent or libvirt or cli 说啥就是啥。这样如果机器 crash，agent 没定时上报，谁去把元数据标记为 unknown

**Comment by jschwinger233** [comment]
4\. core 自己标记. core 开一个 goroutine watch key, 过期就设为 unknown; 不过这样的话 core 的 watch 接口要重新实现, 不能直接转发 watch etcd key

3\. 是参考 k8s pod 有两个状态 succeed / failed 是已经完成运行的 pod, 通过 successfulJobsHistoryLimit / failedJobsHistoryLimit 来清理

1\. 是; 不过现在其实已经有一点点耦合了, healthy 状态必须由 agent 上报, 而 zero 那边有些业务必须依赖 healthy 状态的 refresh 做事; 不过目前也只是 healthy 状态依赖 agent, 而容器生命周期和资源管理依然是不依赖 agent...

**Comment by jschwinger233** [comment]
感觉改动太大, 好处又有限, 还是不要这么搞

**Comment by CMGS** [comment]
4. 这个 core 开 goroutine 就有问题。。如果多个  core，你还得有个分布式锁，不然以哪个 core 的操作为主呢
3. 这个设计的原因在于 api server 和 kubelet 是完全解耦的，后者负责生命周期也只需要关心一台机器的生命周期，core 很难做到这点
1. healthy 其实是算接口定义吧，等于 core 有这个接口，下面无论哪个 agent 都应该 follow 这个接口定义
