### ISSUE TITLE
https://eru.sh/docs/ is 404

### ISSUE THREAD

**Issue by hallkk** [projecteru2/core#204]

**Comment by CMGS** [comment]
@halk947 hi...yep....no docs under this url, you can try https://book.eru.sh/ instead.

**Comment by hallkk** [comment]
> @halk947 hi...yep....no docs under this url, you can try https://book.eru.sh/ instead.

![image](https://user-images.githubusercontent.com/1014928/82972972-dca1df80-a008-11ea-888d-39e045faab76.png)

It's url on  this page

**Comment by CMGS** [comment]
> > @halk947 hi...yep....no docs under this url, you can try https://book.eru.sh/ instead.
> 
> ![image](https://user-images.githubusercontent.com/1014928/82972972-dca1df80-a008-11ea-888d-39e045faab76.png)
> 
> It's url on this page

Oh yes, already modify it now lol, thanks.
