### ISSUE TITLE
exec 接口区分 stdout/stderr (docker engine)

### ISSUE THREAD

**Issue by CMGS** [projecteru2/core#254]

**Comment by jschwinger233** [comment]
原来是这么古老的 issue 了... 
我就是做这个的时候意识到两个 goroutine 同时输出 stdout / stderr 到一个 fd 可能有乱序/覆盖的并发问题, 才引发了组内关于 write(2) 原子性大讨论....

**Comment by jschwinger233** [comment]
目前做到一半.....

**Comment by CMGS** [comment]
https://github.com/projecteru2/core/pull/327
