### ISSUE TITLE
Support core-dump on Docker Container

### ISSUE THREAD

**Issue by atlas-comstock** [projecteru2/core#312]

**Comment by jschwinger233** [comment]
啥意思?

**Comment by jschwinger233** [comment]
看了一下 docker api 没有提供类似功能(有才怪), 所以不就是你自己去调用 exec 接口嘛....
当然需要额外的工具去生成 coredump, 比如 gdb / gcore, 容器里才怪, 比较通用的做法是旁路创建新容器, 使用新的内置了这些工具镜像, 并且 attach pid ns, 就可以了...
当然 coredump 没有符号表也是看不懂的, 我们 go build 都 -s 了, 所以 coredump 用途有限, 甚至完全是应用强相关的, 似乎应该做到 zero-redis 这种特定应用管理层...

**Comment by atlas-comstock** [comment]
@jschwinger23 确实，我先让proxy那边的镜像改改core_pattern好了
