### ISSUE TITLE
Documentation for deploying strategies

### ISSUE THREAD

**Issue by jasonjoo2010** [projecteru2/core#336]
Some strategies like `FILL`, `AUTO` have changed so the current documentation is outdated. Updating is needed to make it up-to-date.

### FILL

In previous versions deployment with no effect will be taken as success.
Now it's taken as a failure.

Reproduce steps:

deploy(1, 1, FILL) -> succ, 1 new instance
deploy(1, 1, FILL) -> fail, 0 new instance
deploy(1, 3, FILL) -> succ, 2 new instance

### AUTO

In previous versions `node limit` took no effect under `AUTO` strategy. But now it's used as the `maximum instances per node` besides similar implementation.

**Comment by CMGS** [comment]
https://github.com/projecteru2/white-paper/pull/12
