### ISSUE TITLE
Enhancement: Retry count should be 0 or omitted with "no" policy

### ISSUE THREAD

**Issue by jasonjoo2010** [projecteru2/core#338]
## Background

In business the restart policy needs to be set to `no`.

## Result Expected

Success.

## Result Actual

Fail with: maximum retry count could be used with policy "no".

## Related Code

container.go:58
```go
// set restart always
restartRetryCount := 3
if opts.RestartPolicy == restartAlways {
    restartRetryCount = 0
}
```

The retry count should be 0 when using `no` policy or just omit it.

## Workaround

Currently a workaround works that is setting policy to empty instead of setting it to `no` explicitly. Better to fix it in future in core.

**Comment by CMGS** [comment]
这里需要屏蔽 restart 逻辑，抽象成 eru 的 restart 逻辑
