### ISSUE TITLE
opti: Stop is too slow

### ISSUE THREAD

**Issue by jasonjoo2010** [projecteru2/core#346]
## Description

We have frequently large bundle of nodes to create and destroy recently.  
But I found that it's very inefficient in the stopping step(maybe also in removing but it's much more efficient)  

## Optimization

Is it possible to turn it from serializing into batches?

**Comment by jschwinger233** [comment]
Core calls docker api to stop containers concurrently just the way core removes containers.
The relative longer waiting for stop is because dockerd implements the `ContainerStop` by sending SIGTERM followed by SIGKILL after some graceful termination interval (10s by default).

**Comment by jasonjoo2010** [comment]
> Core calls docker api to stop containers concurrently just the way core removes containers.
> The relative longer waiting for stop is because dockerd implements the `ContainerStop` by sending SIGTERM followed by SIGKILL after some graceful termination interval (10s by default).

After checking the codes related to control workloads, yes, they are running concurrently not like how it's done in removing(based on step).
So maybe it just cannot be more efficient stopping the workloads.
