### ISSUE TITLE
improve: Refine error message during creation of container

### ISSUE THREAD

**Issue by jasonjoo2010** [projecteru2/core#357]
## Background

The error message during creation of the containers is implicit:

```
[CreateContainer] create container failed Error response from daemon: network cloud-live-sg4 not found
```

It's hard to locate the node complaining the error above. So maybe introduce the node name at least is better for locating the issue.

## Proposal

Introduce more details into the error description to make it easy to locate the complaining node, for example:

```
[CreateContainer] create container failed Error response from daemon: network cloud-live-sg4 not found on sg4-node-10-10-33-34
```

Sure a more fine message is also acceptable.

**Comment by jschwinger233** [comment]
![Image Pasted at 2021-3-16 15-55](https://user-images.githubusercontent.com/6435624/111274666-3d6dd780-8670-11eb-9993-d002cbe985e5.png)


already there in core log, all you need to do is to update to v21.03.15

**Comment by jschwinger233** [comment]
然后发现没有栈日志, 因为没有覆盖到 types module, 生气.....补上补上

**Comment by jasonjoo2010** [comment]
> 然后发现没有栈日志, 因为没有覆盖到 types module, 生气.....补上补上

patpat

SRE should be happy with the name of the node at least.
That's fine~
