### ISSUE TITLE
[Feature Request] Create Workload with Specific ulimit

### ISSUE THREAD

**Issue by jschwinger233** [projecteru2/core#362]
docker api already has this arguments: `docker run --ulimit <type>=<soft>:<hard>`, let's just wrap it.

requested by @jason-joo

**Comment by jasonjoo2010** [comment]
should be @jasonjoo2010

**Comment by jasonjoo2010** [comment]
Though they are two accounts which should all belong to me but I just cannot login into the old account `jason-joo`.

Holly shit
