### ISSUE TITLE
etcdlock.Mutex 的实现并不是一个行为上正确的分布式锁

### ISSUE THREAD

**Issue by tonicmuroq** [projecteru2/core#363]
我们这里使用的是 `concurrency.NewSession(cli, concurrency.WithTTL(ttl))`.  
这个 session 是对 lease 的一个 wrapper, 会一直去 refresh lease 的 ttl, 只要这个 session 还存在, 没有断开或者没有过期, lease 就会一直被刷新.   

这个就导致了 `func New(cli *clientv3.Client, key string, ttl time.Duration) (*Mutex, error)` 这个函数的 `ttl` 会迷惑用户, 这个 `ttl` 并不是非正确释放的情况下的自动释放的时间... 这个 ttl 是说 session 断开了或者锁被释放之后, 再过最多多久 lease 会被释放...  

如下代码并不是预期结果:

```
m1, _ := New(cli, "test", 5*time.Second)
m2, _ := New(cli, "test", 5*time.Second)
m1.Lock(ctx)
m2.Lock(ctx)
```

`m2` 会超时退出, 而不是因为 5s 后 m1 被自动释放所以 m2 顺延拿到锁.

所以建议要么改成正确实现, 要么直接屏蔽掉这个 `ttl`, 默认给给最小值, 在一个持有者非正常退出之后会被很快释放.

**Comment by jschwinger233** [comment]
把这个参数删掉如何, 因为现在已经有用户上锁的时候不希望有超时从而设置了超大的 ttl, 如果正确实现了 timeout 那么设置多大的值又是一个亘古不变的问题.

**Comment by tonicmuroq** [comment]
那么这个锁就变成不会有超时时间了, 只有当 `Unlock` 或者进程意外 crash 之后不再 keepalive 的时候才会过期, 觉得也可以的... 需要超时可以自己在 `Lock` 的 context 参数去添加 timeout ( 但是似乎行为也有点诡异...

**Comment by jschwinger233** [comment]
其实现在提供的锁就是没有超时, 好像也没出现过死锁什么的...
而且应该由调用方自己设置任务超时(

**Comment by tonicmuroq** [comment]
附议直接去掉...
