### ISSUE TITLE
bug: `eru-cli lambda` terminates without any error output when failed

### ISSUE THREAD

**Issue by jasonjoo2010** [projecteru2/core#367]
### Description

`eru-cli` would terminate without any outputs if it actually failed (infer from the logging of `eru-core`). For example use a wrong pod to run a lambda:

```shell
eru-cli lambda --pod masterasdf --name jason-test ls 
```

That the pod `masterasdf` actually doesn't exist. 

### Expected Result

The error like `not enough nodes` in the example above should be returned to `eru-cli`.

**Comment by tonicmuroq** [comment]
fixed by https://github.com/projecteru2/core/pull/387
