### ISSUE TITLE
Goroutine leak at Vibranium.ExecuteWorkload

### ISSUE THREAD

**Issue by jschwinger233** [projecteru2/core#398]
https://github.com/projecteru2/core/blob/77be215e1cf295270b0715cd7ac4453a099d3249/rpc/rpc.go#L700-L712

这个 goroutine 可能会永久阻塞在 `inCh <- execWorkloadOpt.ReplCmd`, 因为 `inCh` 的消费端 goroutine 已经死了.

消费端代码在

https://github.com/projecteru2/core/blob/77be215e1cf295270b0715cd7ac4453a099d3249/cluster/calcium/helper.go#L144-L168

这里的 goroutine 就算遇错也不能 return, 必须等 inCh close.

**Comment by CMGS** [comment]
这都是怎么发现的……
