### ISSUE TITLE
Label filter support on agent

### ISSUE THREAD

**Issue by jasonjoo2010** [projecteru2/core#401]
# Background

In some scenarios one node may be added to different Eru, that is, sort of reusing or sharing.  
By doing this we can share the same node with different types of businesses.
But there is a problem on the agent that it cannot detect which set of containers belonging to it.

# Proposal

* Introduce label filters to agent.
* Better to introduce a new label to containers like ERU_NAME, etc. .

**Comment by jschwinger233** [comment]
叠节点大法的第二春

**Comment by jasonjoo2010** [comment]
> 叠节点大法的第二春

Yeah dude

**Comment by tonicmuroq** [comment]
这个应该是要两个维度切了

* 同样的主机归属于不同的 core, 需要判断容器是否属于这个 core, 甚至可能跟其他集群共存的时候只有部分容器属于 eru
* 同样的主机被多次注册变成不同的 node, 他们属于同一个 core, 需要判断容器是不是属于这个 node
* 上面两种叠加

**Comment by tonicmuroq** [comment]
但是刚刚看了眼 container 上的 label 没有 node 信息... 难道要按照 env 去 filter ... 啊啊啊好恶心

**Comment by CMGS** [comment]
我怎么记得 env 里面有的，可以给 label 加嘛

**Comment by tonicmuroq** [comment]
https://github.com/projecteru2/agent/pull/53

a proposal
