### ISSUE TITLE
New endpoints won't take effects until restarting eru-core

### ISSUE THREAD

**Issue by jasonjoo2010** [projecteru2/core#475]
# Case

We added a proxy layer (eru-barrel) and updated the endpoint for the affected nodes.

# Problem

Core keeps a connection cache and in this case the cache won't update. So all the docker requests will be sent to the old endpoint instead of the latest one.

# Workaround

Restart the eru-core.

Should it be solved or just keep the workaround as the best practice?

**Comment by jschwinger233** [comment]
barrel 应该是新起了端口, 然后 cli node set 修改 endpoint, 然后因为 core 内部 cache 没有更新所以出问题了.

**Comment by jschwinger233** [comment]
Closed by https://github.com/projecteru2/core/pull/492
