### ISSUE TITLE
ERU resource to be plugable

### ISSUE THREAD

**Issue by DuodenumL** [projecteru2/core#487]
目前Core的资源有四种：CPU，Memory，Volume，Storage（[https://github.com/projecteru2/white-paper/blob/master/conception/resource.md](https://github.com/projecteru2/white-paper/blob/master/conception/resource.md)）。在ERU全家桶的代码中，有很多的逻辑都和资源的具体类型过度耦合了，如果我们想要新增一种资源类型，那将是及其巨大的工作量。

因此我们打算把Core里“资源管理”这个功能剥离出来，做成插件的形式。每个“资源插件”都是一个可执行文件的形式，负责管理、计算、分配具体的资源类型。而Core这边的逻辑里并不需要知道什么是CPU，什么是Memory，Core只负责把参数传递给不同的资源插件就好了。

因为有了资源插件化，从此Node的metadata里也不需要存储各种资源的信息了。举个例子，现在的Node Meta是这样的：

```go
{
    "name": "docker0",
    "endpoint": "tcp://10.233.126.165:2377",
    "podname": "docker",
    "labels": null,
    "cpu": {
        "0": 100,
        "1": 100,
        "2": 100,
        "3": 100
    },
    "volume": {
        
    },
    "numa": null,
    "numa_memory": null,
    "memcap": 3040398540,
    "storage_cap": 10737418240,
    "init_cpu": {
        "0": 100,
        "1": 100,
        "2": 100,
        "3": 100
    },
    "init_memcap": 6261624012,
    "init_storage_cap": 10737418240,
    "init_numa_memory": null,
    "init_volume": {
        
    },
    "cpuused": 7,
    "volumeused": 0,
    "available": false
}
```

在资源插件接管资源分配的工作之后，资源相关的信息由插件负责，Node Meta只需要记录：

```go
{
    "name": "docker0",
    "endpoint": "tcp://10.233.126.165:2377",
    "podname": "docker",
    "labels": null,
    "available": false
}
```

可见，如果未来想要新增一种资源类型，只需新增一个资源插件，并部署到指定的目录中，无需修改Core的代码，流程大大地简化了。而且资源插件可以由任意语言编写，可以用任意数据库来存储资源相关的数据，这也极大地加快了开发的效率。

在实现资源插件化后，创建一组workload并分配资源的流程是：（暂定）

1. eru-cli将请求资源相关的参数（以下称为`rawArgs`）以字符串的形式，原封不动地发给`/pb.CoreRPC/CreateWorkload`
2. core收到请求后，会把`rawArgs`发送给所有的资源插件，每个资源插件会各自筛选哪些Node有足够的资源进行后续部署，返回Node列表和一些其他信息（例如当前的资源占用率等）。
3. core把插件返回的列表取交集，得到一个可以满足所有资源分配条件的Node列表。core根据调度策略来确认哪些Node即将用于最终的部署，以及每个Node部署多少个实例。
4. core在部署workload时，将`rawArgs`发送给所有的资源插件，由插件进行资源的分配工作，然后插件返回`engineArgs`，即后续要传递给engine的参数。
5. core汇总所有插件返回的`engineArgs`，调用engine创建workload。
6. 检查是否有创建失败的workload，如有，需要调用资源插件，将其分配的资源还回去。

**Comment by CMGS** [comment]
raw args 你这个不清真啊

**Comment by DuodenumL** [comment]
> raw args 你这个不清真啊

因为如果core真的完全不了解有哪些资源，就没法正确地解析这些参数...

当然rawArgs也可以是map[string][]string的形式，这样稍微清真一些

**Comment by DuodenumL** [comment]
“资源插件化”在很多场景也可以为eru-core提供更多扩展能力。

SRE可能会有一些affinity相关的需求，例如希望“这一组workload不要部署在已经运行了redis的节点上”，就可以自己去实现一个资源插件（暂时称为“affinity插件”）。在部署时，core会把请求参数传给所有的资源插件，affinity插件会将不符合要求的node的capacity设置为0，这样就不会在这些node上部署了。

类似地，如果想实现“当已经使用的storage大于60%就不再部署新workload”，也可以使用资源插件。这个插件可以用任何方式去获取目标node的storage用量，如果发现用量太大了，在core部署时把node capacity设置为0即可。
