### ISSUE TITLE
Migrate selfmon to core

### ISSUE THREAD

**Issue by DuodenumL** [projecteru2/core#523]
最近selfmon上线的过程中发现了一些问题，主要原因是agent -> core -> etcd -> core -> selfmon -> core这一个调用链过于复杂，在agent快速重启的时候，crash时调用的SetNode和重启后selfmon收到消息的SetNode可能近乎同时发生，从而出现各种匪夷所思且不可控的情况。

为了简化这个调用链，降低部署难度，减少出问题的概率，我跟 @jschwinger233 讨论了一下，打算做以下改动：
1. 砍掉单独的selfmon，迁移到core里，逻辑跟之前的大体相似，主要是watch etcd并作出处理，也要有分布式锁，保证多个core只有一个会运行selfmon功能。
2. 把"available"这个字段从node metadata里去掉。GetNode的时候读一下node status，以此来设置node.Available的值。
3. agent常规退出的时候删除node status。
4. agent在重启的时候使用特殊的signal，并且不去删除node status。

这样做的好处：
1. agent重启时，core / selfmon不会有任何感知，也就不会出现那些不可控的情况。
2. 标准的core里就带selfmon的功能，对于agent来说那个enable_selfmon也可以去掉了，可以放心地认为selfmon是一直存在的。
3. GetNode的时候，"available"的值一定和当前的node status一致。
4. 部署的时候方便很多。
5. 调用链变成agent -> core -> etcd，相当精简了。
6. selfmon本身跟agent其实关系不大，但是做到了同一个项目里，一直以来都很难跟不熟悉ERU的人解释...

@CMGS @jschwinger233 @anrs @tonicbupt

**Comment by jschwinger233** [comment]
还是要请领导们看一下 @CMGS  @anrs 

最重要的一点是把 selfmon 的功能移动到 core 内部作为一个 goroutine, 而不是一个单独的服务.

这是因为目前的调用链可能会导致乱序消息, 一次 eru-agent 重启会先发一个 node down 再发一个车 node up, 但是经过多次网络传送之后 core 处理起来可能成先 set node up 再 set node down 了, 非常危险, 所以优化一下调用链路.

同时想办法让 eru-agent 在人工重启(比如升级)的时候不发 node down 消息, 这样再结合 selfmon 功能主体的迁移, 应该能杜绝消息乱序导致的问题.

**Comment by tonicmuroq** [comment]
嗯这样就好像 core 全部 handle 了, 对外提供一个 atomic 的接口了 👍🏼

**Comment by jschwinger233** [comment]
> 嗯这样就好像 core 全部 handle 了, 对外提供一个 atomic 的接口了 👍🏼

https://youtu.be/SbgqJjaaGe0?t=66

**Comment by CMGS** [comment]
LGTM
