### ISSUE TITLE
Use 3rd package to replace Goroutine Pool & WAL

### ISSUE THREAD

**Issue by CMGS** [projecteru2/core#559]
use https://github.com/panjf2000/ants to replace goroutine pool
use https://github.com/tidwall/wal to replace wal

**Comment by jschwinger233** [comment]
goroutine pool 要是不嫌弃简陋的话, 可以用 https://pkg.go.dev/golang.org/x/sync/errgroup

**Comment by CMGS** [comment]
看了下似乎没并发控制？
